### ISSUE TITLE
url handler does not properly escape special characters.

### ISSUE THREAD

**Issue by zcrayfish** [michael-lazar/pygopherd#7]
Hi there, just noticed that the handler for the hURL hack in pygopherd does not escape some characters (via either percent encoding or HTML entities). As a result it is somewhat trivial to insert arbitrary HTML, including javascript, into the generated hURL redirect page.

something along the lines of:
```
curl "gopher://127.0.0.1:7070/hURL:https://www.example.com><script%20type='text/javascript'>alert('I%20am%20an%20alert%20box!');</script>"
```
Please note: in addition to this being an attack vector (admittedly mostly for outdated clients), this also affects users who are not percent encoding their URLs in gophermaps, which is how I original discovered this issue.

**Comment by michael-lazar** [comment]
Hey!

Thanks for reporting this. It's definitely an XSS vulnerability, although I don't know what consequences that would actually have on a gopher server.

In other places in the codebase `html.escape()` is used, so that should be used here too.

I think trying to percent-encode unknown URLs is wrong, because you can never know for certain if the URL was already encoded or not.

I'll patch it and cut a bugfix release soon.

**Comment by michael-lazar** [comment]
I have tagged a v3.0.1 release and uploaded the new version to PyPI.

https://github.com/michael-lazar/pygopherd/releases/tag/v3.0.1

@jgoerzen I'll leave it up to you for how you want to handle this for the Debian package.
